name: docker_build
on: [push]
jobs:
  docker_image_upload:
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/racing_post_scraper:latest
